<?php require('template/header.phtml') ?>
<div class="row" >
        <div class="form-group col-xs-9" >
            Export to CSV.
        <form action = "<?php echo $_SERVER['PHP_SELF']; ?>" method = "post" >
            <input type="submit" value="All sensors" name="export">
            <input type="submit" value="HFT type" name="exportHFT">
            <input type="submit" value="Temp type" name="exportTemp">
        </form>
</div>
</div>
<?php require('template/footer.phtml') ?>