<?php require('template/header.phtml') ?>

<div class="container">
    <div class="row">
        <div class="form-group col-xs-9">
            2016-01-25 15:21:15<br>
            2016-01-25 58:10:10
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <input type="text"  id="startDate" name="startDate" value="2016-01-25 15:21:15">
            <input type="text" id="endDate" name="endDate" value="2016-01-25 15:58:10">
            <br>
            <input type="radio" name="type" value="HFT" <?php if (isset($_POST['type']) && ($_POST['type'] == 'HFT')) echo 'checked="checked" '; ?> > HFT
            <input type="radio" name="type" value="Temp"<?php if (isset($_POST['type']) && ($_POST['type'] == 'Temp')) echo 'checked="checked" '; ?> > Temp
            <input type="radio" name="type" value="All" <?php if (isset($_POST['type']) && ($_POST['type'] == 'All') || !isset($_POST['type'])) echo 'checked="checked" '; ?> >All
                <br>
            <input type="submit" value="search" id="search" name="search">

            </form>
        </div>
    </div>

    <?php if (isset($HFTresults) ): ?>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Node ID</th>
            <th>Sensor Type</th>
            <th>Sensor Name</th>
            <th>Air temperature</th>
            <th>Surface temperature</th>
            <?php if ($_POST['type'] != 'Temp'):?>
                <th> Heat flux </th >
            <?php endif;?>
            <th>Time</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($results as $sensor):?>
            <tr>
                <td>
                    <?php echo $sensor['nodeID']; ?>
                </td>
                <td>
                    <?php echo $sensor['sensor_Type']; ?>
                </td>
                <td>
                    <?php echo $sensor['sensor_Name']; ?>
                </td>
                <td>
                    <?php echo $sensor['air_temp']; ?>
                </td>
                <td>
                    <?php echo $sensor['surface_temp']; ?>
                </td>
                    <?php if (isset($sensor['heat_flux'])){echo '<td>' . $sensor['heat_flux'] . '</td>';}elseif($_POST['type'] == 'All'){
                        echo "<td></td>";
                    } ?>

                <td>
                    <?php echo $sensor['time_stamp']; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
</table>
    <?php endif; ?>
</div>

<?php require('template/footer.phtml') ?>
