<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table class="table table-hover">
        <thead>
        <tr><th>Node ID</th><th>Sensor Name</th><th>Sensor Type</th></tr>

        </thead>
        <tbody>
        <?php
        if(isset($results)):
            foreach ($results as $sensor) {
            $link="sensorData.php?node_id=".$sensor['nodeID']."&type=".$sensor['sensor_Type'];
            echo '<tr><td>' . $sensor['nodeID'] . '</td><td>' . $sensor['sensor_Name'] . '</td><td>' . $sensor['sensor_Type'] . '</td><td><a href='.$link.'>Historical Data</a></td></tr>';
        }
        endif;
        ?>
        </tbody>
    </table>
</form>

<?php require('template/footer.phtml') ?>
