    <div class="row">
        <div id="footer" class="text-center">
            This website is created and designed by group7(Stephen Lilly, Petar Stanev, Bozhidar Marinov,
            Haoyuan Wang, Mihail Sahatchiev).
        </div>
    </div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/datetimepicker/latest/DateTimePicker.min.css" />

</body>
</html>