        <div id="footer" class="text-center">
            <div class="col-md-offset-2 col-md-8">
                This website is created and designed by group7(Stephen Lilly, Petar Stanev, Bozhidar Marinov,
                Haoyuan Wang, Mihail Sahatchiev).
            </div>
        </div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

</body>
</html>