    </div>


    <div class="row footer">
        <div id="footer" class="col-md-offset-2  col-xs-8">
            This website is created and designed by group7(Stephen Lilly, Petar Stanev, Bozhidar Marinov,
            Haoyuan Wang, Mihail Sahatchiev).
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>